# Generated by Django 4.2.7 on 2023-11-07 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('p_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ProductTable',
            },
        ),
    ]
