# Generated by Django 4.2.7 on 2023-11-18 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0002_alter_customertable_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('sales_man', models.CharField(max_length=100)),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_disc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable')),
            ],
            options={
                'db_table': 'SalesTable',
            },
        ),
        migrations.CreateModel(
            name='SaleItemTable',
            fields=[
                ('sale_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.CharField(default=15)),
                ('discount', models.CharField(max_length=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttable')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.salestable')),
            ],
            options={
                'db_table': 'SaleItemTable',
            },
        ),
    ]
